version: 2
jobs:
  node-6-lts:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: npm install
      - run: npm test
  node-8-lts:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
  version: 2
  testing:
    jobs:
      - node-4-lts
      - node-6-lts
      - node-8-lts
      - node-9
